from pathlib import Path
import re,json,html,shutil

R=Path(__file__).resolve().parents[1]; DATA=R/'data/vehicles.json'; BASE='https://jinbacars.com'
langs=['en','zh','ru','ar']
T={
'en':dict(home='Home',inventory='Inventory',process='How it works',services='Services',company='Company',contact='Contact',quote='Get a quote',hero='China used cars, ready for the world.',hero2='Choose verified inventory and coordinate export documents and shipping with one dedicated team.',browse='Browse vehicles',advisor='Talk to an advisor',stock='Verified inventory',popular='Vehicles ready for export',all='View all vehicles',steps='From shortlist to shipment',step1='Share your requirement',step2='Receive a shortlist',step3='Review vehicle details',step4='Confirm quotation',step5='Documents and customs',step6='Ship to your port',cta='Tell us which vehicle you need.',ctap='Send the model, budget and destination port for a quotation.',whatsapp='Start on WhatsApp',year='Year',mileage='Mileage',fuel='Fuel',trans='Transmission',brand='Brand',model='Model',photos='verified photos',onephoto='verified photo',details='Details',search='Search model or brand',filter='Filter',anybrand='All brands',anyfuel='All fuels',anyyear='All years',back='Back to inventory',condition='Vehicle information',desc='Contact us for the current condition report, inspection details and export quotation.',limited='Only the verified photos currently available are shown. More original photos can be added when supplied.',email='Email',location='Xinyu, Jiangxi, China',rights='All rights reserved.'),
'zh':dict(home='首页',inventory='车辆库存',process='采购流程',services='出口服务',company='公司介绍',contact='联系我们',quote='获取报价',hero='中国优质二手车，驶向全球。',hero2='精选真实车源，由专属团队协调出口文件、报关和国际运输。',browse='浏览车辆',advisor='咨询出口顾问',stock='真实车辆库存',popular='适合出口的精选车辆',all='查看全部车辆',steps='从选车到发运，全程服务',step1='告诉我们需求',step2='获取推荐清单',step3='查看车辆资料',step4='确认报价',step5='出口文件与报关',step6='发运至目的港',cta='告诉我们你需要什么车。',ctap='发送车型、预算和目的港，我们为你准备报价。',whatsapp='WhatsApp咨询',year='年份',mileage='里程',fuel='燃料',trans='变速箱',brand='品牌',model='车型',photos='张已验证照片',onephoto='张已验证照片',details='查看详情',search='搜索车型或品牌',filter='筛选',anybrand='全部品牌',anyfuel='全部燃料',anyyear='全部年份',back='返回车辆列表',condition='车辆信息',desc='联系我们获取当前车况报告、检测详情和出口报价。',limited='这里只展示当前已有的真实照片，收到原始照片后可以继续补充。',email='邮箱',location='中国江西省新余市',rights='版权所有。'),
'ru':dict(home='Главная',inventory='Автомобили',process='Как это работает',services='Услуги',company='Компания',contact='Контакты',quote='Получить цену',hero='Автомобили из Китая — для всего мира.',hero2='Проверенный ассортимент, экспортные документы и доставка с одной командой.',browse='Смотреть автомобили',advisor='Связаться с консультантом',stock='Проверенный ассортимент',popular='Автомобили для экспорта',all='Все автомобили',steps='От выбора до отправки',step1='Сообщите требования',step2='Получите подборку',step3='Проверьте данные авто',step4='Подтвердите цену',step5='Документы и таможня',step6='Доставка в ваш порт',cta='Скажите, какой автомобиль вам нужен.',ctap='Отправьте модель, бюджет и порт назначения.',whatsapp='Написать в WhatsApp',year='Год',mileage='Пробег',fuel='Топливо',trans='Коробка',brand='Марка',model='Модель',photos='проверенных фото',onephoto='проверенное фото',details='Подробнее',search='Поиск модели или марки',filter='Фильтр',anybrand='Все марки',anyfuel='Все виды топлива',anyyear='Все годы',back='Назад к списку',condition='Информация об автомобиле',desc='Свяжитесь с нами для получения отчета о состоянии, осмотра и экспортного предложения.',limited='Показаны только доступные проверенные фотографии. Оригинальные фото можно добавить позже.',email='Email',location='Синьюй, Цзянси, Китай',rights='Все права защищены.'),
'ar':dict(home='الرئيسية',inventory='السيارات',process='آلية العمل',services='الخدمات',company='الشركة',contact='اتصل بنا',quote='احصل على عرض',hero='سيارات الصين المستعملة جاهزة للعالم.',hero2='مخزون موثّق ووثائق تصدير وشحن عبر فريق واحد.',browse='تصفح السيارات',advisor='تحدث مع مستشار',stock='مخزون موثّق',popular='سيارات جاهزة للتصدير',all='كل السيارات',steps='من الاختيار إلى الشحن',step1='شارك متطلباتك',step2='استلم قائمة مختارة',step3='راجع بيانات السيارة',step4='أكد العرض',step5='الوثائق والجمارك',step6='الشحن إلى مينائك',cta='أخبرنا بالسيارة التي تحتاجها.',ctap='أرسل الطراز والميزانية وميناء الوصول.',whatsapp='ابدأ عبر واتساب',year='السنة',mileage='الممشى',fuel='الوقود',trans='ناقل الحركة',brand='العلامة',model='الطراز',photos='صور موثّقة',onephoto='صورة موثّقة',details='التفاصيل',search='ابحث عن الطراز أو العلامة',filter='تصفية',anybrand='كل العلامات',anyfuel='كل أنواع الوقود',anyyear='كل السنوات',back='العودة للمخزون',condition='معلومات السيارة',desc='تواصل معنا للحصول على تقرير الحالة وتفاصيل الفحص وعرض التصدير.',limited='نعرض الصور الحقيقية المتاحة فقط، ويمكن إضافة الصور الأصلية لاحقاً.',email='البريد الإلكتروني',location='شينيو، جيانغشي، الصين',rights='جميع الحقوق محفوظة.')}

def clean(x): return re.sub('<[^>]+>','',x).strip()
def extract():
 photos=json.loads((R/'assets/vehicle-images.json').read_text())
 out=[]
 for i in range(1,161):
  p=R/f'cars/{i}/index.html'; s=p.read_text(errors='ignore')
  block=(re.search(r'<div class="detail-info">([\s\S]*?)<div class="detail-cta">',s) or [None,s])[1]
  title=clean((re.search(r'<h1>(.*?)</h1>',block) or [None,f'Vehicle {i}'])[1])
  price=clean((re.search(r'<div class="price">(.*?)</div>',block) or [None,'Ask price'])[1]).replace('USD','').strip()
  specs={clean(a):clean(b) for a,b in re.findall(r'<div class="label">(.*?)</div><div class="value">(.*?)</div>',block)}
  out.append(dict(id=i,title=title,price=price,year=specs.get('年份',''),mileage=specs.get('里程',''),fuel=specs.get('燃料',''),transmission=specs.get('变速箱',''),brand=specs.get('品牌',''),model=specs.get('车型',title),photos=photos.get(str(i),[])))
 return out

def esc(x):return html.escape(str(x),quote=True)
def alt(lang,path='/'):
 return ''.join(f'<a class="{"active" if l==lang else ""}" href="/{l}{path}">{l.upper() if l!="zh" else "中文"}</a>' for l in langs)
def head(lang,title,desc,canonical):
 hre=''.join(f'<link rel="alternate" hreflang="{l}" href="{BASE}/{l}{canonical}">' for l in langs)
 return f'''<!doctype html><html lang="{lang if lang!='zh' else 'zh-CN'}" dir="{'rtl' if lang=='ar' else 'ltr'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)}</title><meta name="description" content="{esc(desc)}"><link rel="canonical" href="{BASE}/{lang}{canonical}">{hre}<link rel="stylesheet" href="/assets/v3.css?v=1"><script defer src="/assets/v3.js?v=1"></script></head><body>'''
def header(lang,path='/'):
 t=T[lang];return f'''<div class="top"><div class="wrap"><span>JINBA AUTO EXPORT · CHINA</span><span><a href="mailto:jian5222@gmail.com">jian5222@gmail.com</a> · <a href="https://wa.me/8618079089999">+86 180 7908 9999</a></span></div></div><header class="header"><nav class="wrap nav"><a class="brand" href="/{lang}/"><span class="mark">J</span><span>JINBA AUTO<small>USED CAR EXPORT</small></span></a><button class="hamb" onclick="toggleNav()" aria-label="Menu">☰</button><div class="navlinks" id="navlinks"><a href="/{lang}/">{t['home']}</a><a href="/{lang}/cars/">{t['inventory']}</a><a href="/{lang}/#process">{t['process']}</a><a href="/{lang}/contact/">{t['contact']}</a><span class="langs">{alt(lang,path)}</span><a class="quote" href="https://wa.me/8618079089999">{t['quote']}</a></div></nav></header>'''

VALUES={'fuel':{'纯电':{'en':'EV','zh':'纯电','ru':'Электро','ar':'كهربائي'},'插混':{'en':'PHEV','zh':'插混','ru':'Гибрид PHEV','ar':'هجين PHEV'},'柴油':{'en':'Diesel','zh':'柴油','ru':'Дизель','ar':'ديزل'},'Petrol':{'en':'Petrol','zh':'汽油','ru':'Бензин','ar':'بنزين'}},'trans':{'自动':{'en':'Automatic','zh':'自动','ru':'Автомат','ar':'أوتوماتيك'},'手动':{'en':'Manual','zh':'手动','ru':'Механика','ar':'يدوي'}}}
def value(lang,key,raw):return VALUES.get(key,{}).get(raw,{}).get(lang,raw)
def footer(lang):
 t=T[lang];return f'''<footer><div class="wrap"><div class="footergrid"><div><h4>JINBA AUTO EXPORT</h4><p>{t['location']}</p></div><div><h4>{t['inventory']}</h4><a href="/{lang}/cars/">{t['all']}</a></div><div><h4>{t['company']}</h4><a href="/{lang}/contact/">{t['contact']}</a></div><div><h4>{t['contact']}</h4><a href="https://wa.me/8618079089999">WhatsApp: +86 180 7908 9999</a><a href="mailto:jian5222@gmail.com">jian5222@gmail.com</a></div></div><div class="copyright">© 2026 Jinba Auto Export. {t['rights']}</div></div></footer></body></html>'''
def card(v,lang):
 t=T[lang]; ph=v['photos'][0] if v['photos'] else '/images/og-image.jpg'; pc=len(v['photos']); fuel=v['fuel'];displayfuel=value(lang,'fuel',fuel);return f'''<a class="card" data-car data-search="{esc((v['title']+' '+v['brand']).lower())}" data-brand="{esc(v['brand'])}" data-fuel="{esc(fuel)}" data-year="{esc(v['year'])}" href="/{lang}/cars/{v['id']}/"><div class="photo"><img loading="lazy" src="{ph}" alt="{esc(v['title'])}"><span class="photo-count">{pc} {t['onephoto'] if pc==1 else t['photos']}</span></div><div class="body"><div class="meta">{esc(v['brand'])} · {esc(v['year'])}</div><h3>{esc(v['title'])}</h3><div class="spec"><span>{esc(v['mileage'])}</span><span>{esc(displayfuel)}</span></div><div class="foot"><span class="price">{esc(v['price'])}</span><span class="more">{t['details']} →</span></div></div></a>'''
def home(lang,V):
 t=T[lang]; hero=V[0]['photos'][0]; featured=''.join(card(v,lang) for v in V[:6]); steps=''.join(f'<article class="step"><h3>{t[f"step{i}"]}</h3></article>' for i in range(1,7));desc=t['hero2']
 return head(lang,f"Jinba Auto Export | {t['inventory']}",desc,'/')+header(lang,'/')+f'''<main><section class="hero"><div class="wrap hero-grid"><div><div class="eyebrow">XINYU · JIANGXI · CHINA</div><h1>{t['hero'].replace('world.','<em>world.</em>').replace('全球。','<em>全球。</em>')}</h1><p>{t['hero2']}</p><div class="actions"><a class="btn primary" href="/{lang}/cars/">{t['browse']}</a><a class="btn secondary" href="https://wa.me/8618079089999">{t['advisor']}</a></div></div><div class="hero-img"><img src="{hero}" alt="Jinba Auto Export vehicle"></div></div></section><div class="wrap stats"><div class="stat"><b>{len(V)}</b><span>{t['inventory']}</span></div><div class="stat"><b>{sum(len(v["photos"]) for v in V)}</b><span>REAL PHOTOS</span></div><div class="stat"><b>4</b><span>LANGUAGES</span></div><div class="stat"><b>1-to-1</b><span>{t['advisor']}</span></div></div><section class="section"><div class="wrap"><div class="head"><div><div class="kicker">{t['stock']}</div><h2>{t['popular']}</h2></div><a href="/{lang}/cars/">{t['all']} →</a></div><div class="grid">{featured}</div></div></section><section class="section alt" id="process"><div class="wrap"><div class="head"><div><div class="kicker">EXPORT PROCESS</div><h2>{t['steps']}</h2></div></div><div class="steps">{steps}</div></div></section><section class="section"><div class="wrap cta"><div><h2>{t['cta']}</h2><p>{t['ctap']}</p></div><a class="btn" href="https://wa.me/8618079089999">{t['whatsapp']} →</a></div></section></main>'''+footer(lang)
def inventory(lang,V):
 t=T[lang];brands=sorted(set(v['brand'] for v in V if v['brand']));fuels=sorted(set(v['fuel'] for v in V if v['fuel']));years=sorted(set(v['year'] for v in V if v['year']),reverse=True)
 opts=lambda xs,label: '<option value="">'+label+'</option>'+''.join(f'<option>{esc(x)}</option>' for x in xs);fuelopts='<option value="">'+t['anyfuel']+'</option>'+''.join(f'<option value="{esc(x)}">{esc(value(lang,"fuel",x))}</option>' for x in fuels)
 return head(lang,f"{t['inventory']} | Jinba Auto Export",t['stock'],'/cars/')+header(lang,'/cars/')+f'''<section class="pagehead"><div class="wrap"><h1>{t['inventory']}</h1><p>{len(V)} · {t['stock']}</p></div></section><main class="section"><div class="wrap"><div class="filters"><input id="q" placeholder="{t['search']}"><select id="brand">{opts(brands,t['anybrand'])}</select><select id="fuel">{fuelopts}</select><select id="year">{opts(years,t['anyyear'])}</select><button onclick="filterCars()">{t['filter']}</button></div><div class="grid">{''.join(card(v,lang) for v in V)}</div></div></main>'''+footer(lang)
def detail(lang,v):
 t=T[lang];imgs=v['photos'];main=imgs[0] if imgs else '/images/og-image.jpg';thumbs=''.join(f'<button class="thumb {"active" if i==0 else ""}" onclick="setMain(\'{p}\',this)"><img loading="lazy" src="{p}" alt="{esc(v["title"])} photo {i+1}"></button>' for i,p in enumerate(imgs));pc=len(imgs);specs=[('year',v['year']),('mileage',v['mileage']),('fuel',value(lang,'fuel',v['fuel'])),('trans',value(lang,'trans',v['transmission'])),('brand',v['brand']),('model',v['model'])]
 schema=json.dumps({'@context':'https://schema.org','@type':'Vehicle','name':v['title'],'image':[BASE+x for x in imgs],'vehicleModelDate':v['year'],'mileageFromOdometer':{'@type':'QuantitativeValue','value':re.sub(r'\D','',v['mileage']) or 0,'unitCode':'KMT'}},ensure_ascii=False)
 return head(lang,f"{v['title']} | Jinba Auto Export",t['desc'],f"/cars/{v['id']}/")+f'<script type="application/ld+json">{schema}</script>'+header(lang,f"/cars/{v['id']}/")+f'''<main class="section"><div class="wrap"><a href="/{lang}/cars/">← {t['back']}</a><div class="detail" style="margin-top:22px"><div><div class="mainphoto"><img id="mainphoto" src="{main}" alt="{esc(v['title'])}"></div><div class="thumbs">{thumbs}</div><span class="verified">✓ {pc} {t['onephoto'] if pc==1 else t['photos']}</span></div><div><h1>{esc(v['title'])}</h1><div class="bigprice">{esc(v['price'])}</div><div class="specgrid">{''.join(f'<div class="specitem"><small>{t[k]}</small><b>{esc(val)}</b></div>' for k,val in specs)}</div><div class="notice">{t['limited']}</div><h3>{t['condition']}</h3><p class="desc">{t['desc']}</p><div class="actions"><a class="btn primary" href="https://wa.me/8618079089999?text=Jinba%20Auto%20vehicle%20{v['id']}">{t['quote']}</a><a class="btn" style="border-color:var(--line)" href="mailto:jian5222@gmail.com?subject=Vehicle%20{v['id']}">{t['email']}</a></div></div></div></div></main>'''+footer(lang)
def contact(lang):
 t=T[lang];return head(lang,f"{t['contact']} | Jinba Auto Export",t['ctap'],'/contact/')+header(lang,'/contact/')+f'''<section class="pagehead"><div class="wrap"><h1>{t['contact']}</h1><p>{t['ctap']}</p></div></section><main class="section"><div class="wrap contactbox"><div class="contactcard"><h3>WhatsApp</h3><a href="https://wa.me/8618079089999">+86 180 7908 9999</a></div><div class="contactcard"><h3>{t['email']}</h3><a href="mailto:jian5222@gmail.com">jian5222@gmail.com</a></div><div class="contactcard"><h3>{t['location']}</h3><p>Jinba Auto Export</p></div><div class="contactcard"><h3>{t['quote']}</h3><a class="btn primary" href="https://wa.me/8618079089999">{t['whatsapp']}</a></div></div></main>'''+footer(lang)
def write(p,s):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(s)
V=json.loads(DATA.read_text()) if DATA.exists() else extract();DATA.parent.mkdir(exist_ok=True);DATA.write_text(json.dumps(V,ensure_ascii=False,indent=2))
# IDs 1, 2, 5 and 6 only contain generated placeholder artwork, not real vehicle photos.
# Keep them out of public inventory until original photos are supplied. IDs 3 and 4
# have nine real detail photos; discard their placeholder primary and promote photo 1.
for v in V:
 if v['id'] in (3,4):v['photos']=[p for p in v['photos'] if not p.endswith('/primary.jpg')]
V=[v for v in V if v['id'] not in (1,2,5,6)]
for l in langs:
 for i in (1,2,5,6):shutil.rmtree(R/l/f'cars/{i}',ignore_errors=True)
for l in langs:
 write(R/l/'index.html',home(l,V));write(R/l/'cars/index.html',inventory(l,V));write(R/l/'contact/index.html',contact(l))
 for v in V:write(R/l/f'cars/{v["id"]}/index.html',detail(l,v))
write(R/'index.html','<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=/en/"><link rel="canonical" href="https://jinbacars.com/en/"><title>Jinba Auto Export</title>')
write(R/'cars/index.html','<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=/en/cars/"><link rel="canonical" href="https://jinbacars.com/en/cars/">')
published={v['id'] for v in V}
for i in range(1,161):
 target=f'/en/cars/{i}/' if i in published else '/en/cars/'
 write(R/f'cars/{i}/index.html',f'<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url={target}"><link rel="canonical" href="https://jinbacars.com{target}">')
for p in (R/'cars').glob('*.html'):p.unlink()
urls=[f'{BASE}/{l}/' for l in langs]+[f'{BASE}/{l}/cars/' for l in langs]+[f'{BASE}/{l}/contact/' for l in langs]+[f'{BASE}/{l}/cars/{v["id"]}/' for l in langs for v in V]
write(R/'sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{u}</loc></url>' for u in urls)+'</urlset>')
print('vehicles',len(V),'pages',len(urls))
